export const clinicConfig = {
  name: "Smile Dental Clinic",
  address: "123 Main Street, Newmarket, ON L3Y 4Z1",
  phone: "(905) 555-0123",
  email: "info@smiledental.ca",
  hours: {
    weekdays: "8:00 AM – 6:00 PM",
    saturday: "9:00 AM – 2:00 PM",
    sunday: "Closed",
  },
  hoursDetailed: [
    { day: "Monday", hours: "8:00 AM – 6:00 PM" },
    { day: "Tuesday", hours: "8:00 AM – 6:00 PM" },
    { day: "Wednesday", hours: "8:00 AM – 6:00 PM" },
    { day: "Thursday", hours: "8:00 AM – 6:00 PM" },
    { day: "Friday", hours: "8:00 AM – 6:00 PM" },
    { day: "Saturday", hours: "9:00 AM – 2:00 PM" },
    { day: "Sunday", hours: "Closed" },
  ],
  dentists: [
    {
      id: 1,
      name: "Dr. Sarah Chen",
      specialty: "General & Cosmetic Dentistry",
      bio: "Dr. Chen has over 15 years of experience in general and cosmetic dentistry. She is passionate about helping patients achieve their best smile through personalized treatment plans and gentle care.",
      avatar_url: "",
    },
    {
      id: 2,
      name: "Dr. Michael Park",
      specialty: "Orthodontics & Invisalign",
      bio: "Dr. Park is a board-certified orthodontist specializing in Invisalign and modern braces. He has transformed thousands of smiles and is known for his meticulous attention to detail.",
      avatar_url: "",
    },
    {
      id: 3,
      name: "Dr. Priya Sharma",
      specialty: "Pediatric Dentistry & Root Canals",
      bio: "Dr. Sharma specializes in pediatric dentistry and endodontics. Her gentle approach makes children feel at ease, and her expertise in root canals ensures painless procedures for adults.",
      avatar_url: "",
    },
  ],
  services: [
    {
      name: "Checkups",
      icon: "🦷",
      description: "Comprehensive dental examinations to maintain your oral health. Includes digital X-rays and personalized treatment planning.",
      price: "From $150",
    },
    {
      name: "Cleanings",
      icon: "🪥",
      description: "Professional teeth cleaning to remove plaque and tartar buildup. Keep your teeth and gums healthy with regular cleanings.",
      price: "From $120",
    },
    {
      name: "Whitening",
      icon: "✨",
      description: "Professional teeth whitening for a brighter, more confident smile. Choose from in-office or take-home whitening options.",
      price: "From $350",
    },
    {
      name: "Fillings",
      icon: "🔧",
      description: "Tooth-colored composite fillings to restore decayed teeth. Natural-looking results that blend seamlessly with your smile.",
      price: "From $200",
    },
    {
      name: "Crowns",
      icon: "👑",
      description: "Custom dental crowns to protect and restore damaged teeth. Made with high-quality materials for a perfect fit.",
      price: "From $900",
    },
    {
      name: "Root Canals",
      icon: "🏥",
      description: "Painless root canal therapy to save infected teeth. Modern techniques ensure a comfortable experience.",
      price: "From $700",
    },
    {
      name: "Implants",
      icon: "🦿",
      description: "Permanent dental implants to replace missing teeth. Look and feel like natural teeth with long-lasting results.",
      price: "From $3,000",
    },
    {
      name: "Invisalign",
      icon: "😁",
      description: "Clear aligners for discreet teeth straightening. Achieve a perfect smile without traditional metal braces.",
      price: "From $4,500",
    },
    {
      name: "Pediatric",
      icon: "👶",
      description: "Gentle dental care designed for children. Creating positive dental experiences from the very first visit.",
      price: "From $100",
    },
    {
      name: "Emergency",
      icon: "🚨",
      description: "Same-day emergency dental care for urgent issues. We're here when you need us most — call us right away.",
      price: "Call for pricing",
    },
  ],
};
